# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 400)
        MainWindow.setStyleSheet("color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ID = QtWidgets.QTextEdit(self.centralwidget)
        self.ID.setGeometry(QtCore.QRect(120, 50, 104, 41))
        self.ID.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ID.setToolTipDuration(-1)
        self.ID.setFrameShape(QtWidgets.QFrame.Box)
        self.ID.setObjectName("ID")
        self.Pot = QtWidgets.QTextEdit(self.centralwidget)
        self.Pot.setGeometry(QtCore.QRect(580, 50, 104, 41))
        self.Pot.setFrameShape(QtWidgets.QFrame.Box)
        self.Pot.setObjectName("Pot")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.label_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 50, 111, 31))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 10, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setToolTipDuration(-5)
        self.label_7.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_7.setIndent(-10)
        self.label_7.setObjectName("label_7")
        self.Name = QtWidgets.QTextEdit(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(330, 50, 104, 41))
        self.Name.setFrameShape(QtWidgets.QFrame.Box)
        self.Name.setObjectName("Name")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 50, 91, 31))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setObjectName("label_3")
        self.english = QtWidgets.QPushButton(self.centralwidget)
        self.english.setGeometry(QtCore.QRect(260, 290, 75, 23))
        self.english.setStyleSheet("selection-color: rgb(85, 255, 0);")
        self.english.setObjectName("english")
        self.vietnam = QtWidgets.QPushButton(self.centralwidget)
        self.vietnam.setGeometry(QtCore.QRect(400, 290, 75, 23))
        self.vietnam.setObjectName("vietnam")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(520, 290, 75, 23))
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(630, 290, 75, 23))
        self.stop.setObjectName("stop")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(710, 50, 101, 41))
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setObjectName("label_6")
        self.Notice = QtWidgets.QTextEdit(self.centralwidget)
        self.Notice.setGeometry(QtCore.QRect(820, 50, 131, 41))
        self.Notice.setObjectName("Notice")
        self.Chat = QtWidgets.QTextEdit(self.centralwidget)
        self.Chat.setGeometry(QtCore.QRect(190, 110, 541, 161))
        self.Chat.setObjectName("Chat")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 151, 101))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "ID riêng của bạn"))
        self.label_2.setText(_translate("MainWindow", "Pot riêng của bạn"))
        self.label_7.setText(_translate("MainWindow", "Sever chat private"))
        self.label_3.setText(_translate("MainWindow", "Tên của bạn"))
        self.english.setText(_translate("MainWindow", "English"))
        self.vietnam.setText(_translate("MainWindow", "VietNam"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.label_6.setText(_translate("MainWindow", "Bảng thông báo"))
        self.label_4.setText(_translate("MainWindow", "Bảng nhắn tin trung tâm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
