# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerWindow(object):
    def setupUi(self, ServerWindow):
        ServerWindow.setObjectName("ServerWindow")
        ServerWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(ServerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_ip = QtWidgets.QLabel(self.centralwidget)
        self.label_ip.setObjectName("label_ip")
        self.verticalLayout.addWidget(self.label_ip)
        self.host_input = QtWidgets.QLineEdit(self.centralwidget)
        self.host_input.setObjectName("host_input")
        self.verticalLayout.addWidget(self.host_input)
        self.label_port = QtWidgets.QLabel(self.centralwidget)
        self.label_port.setObjectName("label_port")
        self.verticalLayout.addWidget(self.label_port)
        self.port_input = QtWidgets.QLineEdit(self.centralwidget)
        self.port_input.setObjectName("port_input")
        self.verticalLayout.addWidget(self.port_input)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setObjectName("start_button")
        self.verticalLayout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setEnabled(False)
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout.addWidget(self.stop_button)
        self.label_log = QtWidgets.QLabel(self.centralwidget)
        self.label_log.setObjectName("label_log")
        self.verticalLayout.addWidget(self.label_log)
        self.log_display = QtWidgets.QTextEdit(self.centralwidget)
        self.log_display.setReadOnly(True)
        self.log_display.setObjectName("log_display")
        self.verticalLayout.addWidget(self.log_display)
        self.label_chat = QtWidgets.QLabel(self.centralwidget)
        self.label_chat.setObjectName("label_chat")
        self.verticalLayout.addWidget(self.label_chat)
        self.message_input = QtWidgets.QTextEdit(self.centralwidget)
        self.message_input.setObjectName("message_input")
        self.verticalLayout.addWidget(self.message_input)
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setObjectName("send_button")
        self.verticalLayout.addWidget(self.send_button)
        ServerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ServerWindow)
        QtCore.QMetaObject.connectSlotsByName(ServerWindow)

    def retranslateUi(self, ServerWindow):
        _translate = QtCore.QCoreApplication.translate
        ServerWindow.setWindowTitle(_translate("ServerWindow", "Server Chat"))
        self.label_ip.setText(_translate("ServerWindow", "Địa chỉ IP:"))
        self.host_input.setPlaceholderText(_translate("ServerWindow", "Nhập địa chỉ IP"))
        self.host_input.setText(_translate("ServerWindow", "127.0.0.1"))
        self.label_port.setText(_translate("ServerWindow", "Cổng:"))
        self.port_input.setPlaceholderText(_translate("ServerWindow", "Nhập cổng"))
        self.port_input.setText(_translate("ServerWindow", "12345"))
        self.start_button.setText(_translate("ServerWindow", "Bắt đầu Server"))
        self.stop_button.setText(_translate("ServerWindow", "Dừng Server"))
        self.label_log.setText(_translate("ServerWindow", "Thông tin server:"))
        self.label_chat.setText(_translate("ServerWindow", "Gửi tin nhắn đến tất cả client:"))
        self.message_input.setPlaceholderText(_translate("ServerWindow", "Nhập tin nhắn để gửi..."))
        self.send_button.setText(_translate("ServerWindow", "Gửi tin nhắn"))
